default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gym_helper_development

test:
  <<: *default
  database: gym_helper_test

production:
  <<: *default
  database: gym_helper_production
  username: deploy
  password: deploy
