default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gym_helper_development

test:
  <<: *default
  database: gym_helper_test

production:
  <<: *default
  database: gym-helper-production
  host: gym-helper-production.c1p6ayd7hxa9.us-east-1.rds.amazonaws.com
  username: postgres
  password: postgres
