default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gym_helper_development

test:
  <<: *default
  database: gym_helper_test

production:
  <<: *default
  database: gym-helper-production
  username: postgres
  password: postgres
